/* BASIC SETTINGS */
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+08:00";

/* CREATE DATABASE*/
CREATE DATABASE driverless_members;
USE driverless_members;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for faq
-- ----------------------------
DROP TABLE IF EXISTS `faq`;
CREATE TABLE `faq`  (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Category` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `Sub_Category` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `Topic` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `Detail` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 26 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`  (
  `User_Name` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `Password` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `Full_Name` varchar(60) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `Email_Address` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `Date_Of_Birth` date NULL DEFAULT NULL,
  `Post_Address` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `Post_Code` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `Account_Status` int(11) NOT NULL,
  `Continue_Fail_Count` int(11) NULL DEFAULT 0,
  `Date_Of_Create` datetime(0) NULL DEFAULT current_timestamp(),
  `News_Subscription` tinyint(1) NULL DEFAULT NULL,
  PRIMARY KEY (`User_Name`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO `user`(`User_Name`, `Password`, `Full_Name`, `Email_Address`, `Date_Of_Birth`, `Post_Address`, `Post_Code`, `Account_Status`, `Continue_Fail_Count`, `Date_Of_Create`, `News_Subscription`) VALUES ('aaa', 'bbb', 'Good Man', 'test@test.com', '1982-12-05', 'ABC', 'ABC', 1, 0, '2022-11-30 21:18:26', 1);
INSERT INTO `user`(`User_Name`, `Password`, `Full_Name`, `Email_Address`, `Date_Of_Birth`, `Post_Address`, `Post_Code`, `Account_Status`, `Continue_Fail_Count`, `Date_Of_Create`, `News_Subscription`) VALUES ('bbb', 'ccc', 'Bat Man', 'something@test.com', '1999-12-31', 'Your Home Too', 'Your Home ', 1, 0, '2022-11-30 22:06:13', 0);

INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (1, 'FAQ', 'Electric Vehicles in Hong Kong', 'Electric Vehicles in Hong Kong: Where We Are At Now', 'In 2020, electric private vehicles made up 2.7% of private cars in Hong Kong. Despite it being a relatively small percentage, statistics have shown an increasing acceptance of electric vehicles (EVs) among the public. In 2010, the percentage of electric vehicles among all new private cars was just 0.1%. This percentage grew to 5.1% in 2015 and to 12.4% in 2020.\n\nWe can expect an increase in electric vehicle ownership in Hong Kong as more options are continually introduced into the market. As of 31 May 2021. As of 31 May 2021, 138 electric vehicle models have been approved by the Transport Department, of which 103 models are private vehicle models. The government is constantly updating this list so that the electric vehicle becomes more accessible in Hong Kong.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (2, 'FAQ', 'Electric Vehicles in Hong Kong', 'Electric Vehicles are Here to Stay — and Here\'s Why', 'The most obvious reason to drive an electric vehicle is the environmental benefits. Without tailpipe emissions from diesel and gas powered vehicles, the emission of CO2 and other poisonous gases that contribute to air pollution and global warming is greatly reduced. Furthermore, compared to combustion engines, electric motors are more energy efficient.\n\nLong-term cost effectiveness of electric motors compared to internal combustion engines is another reason why many car owners in Hong Kong are considering switching to electric vehicles. Unlike gasoline prices, which fluctuates constantly due to international trends and situations, electricity cost is much more stable.\n\nBattery range is another top concern for electric vehicle shoppers when deciding which vehicle to purchase. Newer models introduced in the last two years generally have a range of over 300km under a single charge, with some even exceeding 500km, demonstrating how electric vehicles are slowly catching up with the range of conventional gas-powered vehicles. For example, the fully electric Tesla Model 3 Long Range AWD has a range of 580km (WLTP) on a single charge.\n\nAs the global trend to promote electric vehicles gains momentum, the Hong Kong government is likewise planning on stopping all new registration of internal combustion private cars, including hybrid vehicles, in 2035 or earlier. There are plans underway to make the city more EV-ready, including expanding its charging network to enable owners to charge their electric vehicles at their homes or at public charging stations. Hong Kong aims to have at least 150,000 chargers in private buildings by 2025. There will also be more specialised education and training for technicians and mechanics to make EV maintenance services more widely available.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (3, 'FAQ', 'Electric Vehicles in Hong Kong', 'Financial Incentives to Promote Use of Evs', 'In addition to making Hong Kong more EV-friendly, the government is also offering financial incentives to promote the use of EVs. Existing First Registration Tax (FRT) Concessions for Electric Vehicles and One-for-One Replacement Scheme have recently been extended to 31 March 2024. The FRT for electric private vehicles will continue to be waived for up to HK$97,500. The One-for-One Replacement Scheme, which provides higher FRT concessions to car owners who scrap and de-register their old fuel-propelled private cars before registering a new electric vehicle, has also been updated. From 24 February 2021 to 31 March 2024, EV owners can enjoy a raised FRT concession cap of $287,500, an increase from the previous cap of HK$250,000, under the One-for-One Replacement Scheme. These incentives encourage new and existing car owners to opt for electric vehicles.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (4, 'FAQ', 'Electric Vehicles in Hong Kong', 'EV Insurance: Third-Party vs. Comprehensive Car Insurance', 'Just like any other types of vehicles being used in Hong Kong, EV owners and drivers are responsible for ensuring they have valid third-party risks coverage with a minimum coverage of HK$100,000,000 for the concerned vehicles. Although the laws only stipulate that owners purchase a third-party risks insurance policy, owners should carefully review whether the coverage from those insurance policies is sufficient.\n\nThird-party-only car insurance, in general, only covers bodily injuries, death and property damage to third parties in case of an accident. Damages to the insured’s vehicle are not covered. Comprehensive car insurance policies not only cover everything third-party-only policies do, but also the insured’s vehicle and extra benefits such as towing/roadside service and personal accident coverage for the insured.\n\nAn important aspect of driving an EV is charging the vehicle. When deciding the extent of insurance coverage, owners should also consider the potential risks that may come with it. For instance, Liberty Insurance’s InsureMyTesla, a comprehensive mileage-based program, offers Charger Liabilities Protection and Wall Connector Coverage for Tesla electric vehicle owners. It covers the replacement costs of private electric chargers and accidents and damages caused by direct usage of designated chargers.\n\nAdditionally, choosing a manufacturer-appointed insurer can ensure one’s motor insurance coverage is tailored to the unique needs of their vehicles. As the authorised insurer of Tesla Hong Kong, Liberty Insurance receives the latest updates regarding Tesla motors and is constantly making sure that the InsureMyTesla coverage is keeping up with these updates.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (5, 'Knowledge', 'Electric Car Knowledge', 'Advantages of Electric Vehicles', 'Electric motors can generate high power-to-weight ratios. Electric motors generally have a plane torque curve down to zero velocity. For reliability, most electric cars have fixed-ratio gearboxes. They do not have a clutch. Numerous electric vehicles have much faster acceleration than their average ICE counterparts. This is mainly due to lesser drivetrain frictional losses and the fast torque of an electric motor.\n\nElectric vehicles have the potential to fix motors in each wheel or adjacent to the wheels. Even though this is rare, it is claimed to be much safer. Electric vehicles that do not have a differential or axle can have less drivetrain inertia. DC motor equipped drag racer EVs possess basic two-speed manual transmission to boost top speed.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (6, 'Knowledge', 'Main Components', 'Battery', 'The auxiliary battery gives electricity to power vehicle accessories in an electric vehicle.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (7, 'Knowledge', 'Main Components', 'DC/DC Converter', 'The device transforms the higher-voltage DC power of the traction battery module into the lower-voltage DC power necessary to activate vehicle components and recharge the battery.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (8, 'Knowledge', 'Main Components', 'Electric Traction Motor', 'This motor uses the power from the battery pack to propel the vehicle’s wheels.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (9, 'Knowledge', 'Main Components', 'Charge Port', 'The charge port connects the vehicle to an external power source for charging the traction battery pack.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (10, 'Knowledge', 'Main Components', 'Power Electronic Controller', 'Regulates the flow of electrical energy provided by the traction battery, regulating the motion of the electric traction motor and the torque it generates.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (11, 'Knowledge', 'Main Components', 'Thermal System (cooling)', 'The thermal system preserves an ideal operating temperature range on the electric motor, power electrics, electric engine, and other components.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (12, 'Knowledge', 'Main Components', 'Transmission', 'The transmission gives the electric traction motor mechanical power to propel the wheels.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (13, 'Knowledge', 'Main Components', 'The onboard Charger', 'Takes the AC electricity supplied through the charging port and transforms it into DC power to fuel the traction battery. It also communicates with the charging component and analyses battery characteristics such as current, temperature, charge state, and voltage while charging the module.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (14, 'Knowledge', 'Main Components', 'Traction Battery Pack', 'It stores electricity for the electric traction motor.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (15, 'FAQ', 'Important QA', 'What is an electric car?', 'An electric car is an automobile driven by electric motors that only uses energy accumulated in batteries. Compared with internal combustion engine vehicles, electric vehicles have no exhaust emissions and are quieter. Electric vehicles or EVs are also usually called electric battery vehicles. They possess an electric motor in place of an internal combustion engine. These vehicles employ a large traction battery module to power the electric motor. Electric vehicle supply equipment or EVSE is the device that batteries are charged. As these vehicles run on electricity, the vehicle emits almost no residue from tailpipes. They do not have the usual liquid fuel parts like a fuel line, fuel tank or fuel pump.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (16, 'FAQ', 'Important QA', 'What is the significance of electric vehicles?', 'Electric motors can generate high power-to-weight ratios. Electric motors generally have a plane torque curve down to zero velocity. Most electric cars have fixed-ratio gearboxes for reliability, but they do not have a clutch.\n\nNumerous electric vehicles have much faster acceleration than their average ICE counterparts. This is mainly due to lesser drivetrain frictional losses and the fast torque of an electric motor.\n\nElectric vehicles have the potential to fix motors in each wheel or adjacent to the wheels. Even though this is rare, it is claimed to be much safer. Electric vehicles that do not have a differential or axle can have less drivetrain inertia. DC motor equipped drag racer EVs possess basic two-speed manual transmission to boost top speed.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (17, 'FAQ', 'Important QA', 'What are the main components of an electric car?', 'The main components of an electric car are an auxiliary battery, DC/DC converter, electric traction motor, charge port, power electronics controller, thermal system, transmission, onboard charger, and ction battery pack.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (18, 'FAQ', 'Important QA', 'What is the function of an auxiliary battery in electric vehicles?', 'The auxiliary battery gives electricity to power vehicle accessories in an electric vehicle.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (19, 'FAQ', 'Important QA', 'What is the function of a DC/DC converter in electric vehicles?', 'The device transforms the higher-voltage DC power of the traction battery module into the lower-voltage DC power necessary to activate vehicle components and recharge the battery.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (20, 'FAQ', 'Important QA', 'What is the function of an electric traction motor in electric vehicles?', 'This motor uses the power from the battery pack to propel the vehicle’s wheels.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (21, 'FAQ', 'Important QA', 'What is the function of a charge port in electric vehicles?', 'The charge port connects the vehicle to an external power source for charging the traction battery pack.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (22, 'FAQ', 'Important QA', 'What is the function of a power electronics controller in electric vehicles?', 'The power electronics controller regulates the flow of electrical energy provided by the traction battery, regulating the motion of the electric traction motor and the torque it generates.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (23, 'FAQ', 'Important QA', 'What is the function of a thermal system in electric vehicles?', 'The thermal system preserves an ideal operating temperature range on the electric motor, power electrics, electric engine, and other components.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (24, 'FAQ', 'Important QA', 'What is the function of transmission in electric vehicles?', 'The transmission gives the electric traction motor mechanical power to propel the wheels.');
INSERT INTO `faq`(`ID`, `Category`, `Sub_Category`, `Topic`, `Detail`) VALUES (25, 'FAQ', 'Important QA', 'What is the function of an onboard charger in electric vehicles?', 'It takes the AC electricity supplied through the charging port and transforms it into DC power for fueling the traction battery. It also communicates with the charging component and analyses battery characteristics such as current, temperature, charge state, and voltage while charging the module.');
